### ISSUE TITLE
host key gather  does not work without backslashes on windows

### ISSUE THREAD

**Issue by jpfleischer** [cloudmesh/cloudmesh-common#31]
See the following git bash output:
```bash
Sledgehammer@Sledgehammer MINGW64 ~
$ cms host key gather "red,red0[1-4]" ~/.ssh/cluster_red_keys

... some great key output here ...

Command File argument C:UsersSledgehammer.sshcluster_red_keys
command filename C:UsersSledgehammer.sshcluster_red_keys
command directory C:
# Timer: 3.4278s Load: 0.0040s host key gather red,red0[1-4] C:/Users/Sledgehammer/.ssh/cluster_red_keys
(ENV3)
```

the issue is that `~/.ssh/cluster_red_keys` becomes interpreted as C:UsersSledgehammer.sshcluster_red_keys

Solution is to use `cms host key gather "red,red0[1-4]" \"~/.ssh/cluster_red_keys\"`

**Comment by laszewsk** [comment]
can you try this agian as I fixed the shlex with a windows shlex

**Comment by jpfleischer** [comment]
the problem has been fixed now that cloudmesh has been updated with windows shlex.
