### ISSUE TITLE
windows: test fails on github actions

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-common#52]
self = <tests.test_verbose.Test_Verbose object at 0x0000021F7849C410>
see :https://github.com/cloudmesh/cloudmesh-common/actions/runs/7233342461/job/19708496081#step:7:1012

    def test_6_print_VERBOSE(self):
        HEADING()
    
        help = "hallo"
    
        for v in [0,1,2,3,4,5,6,7,8,9,10]:
            print("TEST FOR VERBOSE", v)
            with io.StringIO() as buf, redirect_stdout(buf):
                variables["verbose"] = v
                VERBOSE(help, verbose=6)
                output = buf.getvalue()
            print (output)
    
            if v < 6:
>               assert "hallo" not in output
E               AssertionError: assert 'hallo' not in '\x1b[34m\n#...-\n\x1b[0m\n'
E                 'hallo' is contained here:
E                   ------
E                   # 'hallo'
E                   # ----------------------------------------------------------------------
E

**Comment by laszewsk** [comment]
I have outcommented the test for now so we can move on

**Comment by laszewsk** [comment]
this seems only to happen on windows. maybe the stringio on windows does not behave right

**Comment by laszewsk** [comment]
more failed tests for windows :+1: 
https://github.com/cloudmesh/cloudmesh-common/actions/runs/7240790731/job/19724167304

**Comment by laszewsk** [comment]
i had to disable all windows checks in the yaml file as they failed and i do not have a windows machine to fix them

**Comment by laszewsk** [comment]
I suggest splitting up the actions into two different YAML files.

test-via-conda-linux.yaml 
test-via-conda-windows.yaml

I out-commented in the current test the Windows task.
I have not done many Github actions and I hope that by separating them it is easier to switch one off and on in case something does not work.

**Comment by jpfleischer** [comment]
fixed in https://github.com/cloudmesh/cloudmesh-common/pull/58
